### ISSUE TITLE
aemSync not working

### ISSUE THREAD

**Issue by ahahn95** [Cognifide/gradle-aem-multi#62]
I assume the aemSync gradle task will synchronize the files from the AEM instance with the gradle project files. However, when I run the error that the JCR repositories don't exists, also, I keep getting errors such as 

    Execution failed for task ':aem:aemSatisfy'.
    > Cannot list packages on LocalInstance(httpUrl='http://localhost:4502', user='admin', password='*****', typeName='author', debugPort=14502). Reason: request failed.

**Comment by pun-ky** [comment]
You just showed me an error corresponding to task aemSatisfy but wanted to have working aemSync 😉 these are separate things. I suspect that you are probably Gradle beginner, please ensure that you will understand which task you are running and when first, because without that I cannot help you. This Gradle basics are just essential. I am recommending to practice with examples from docs / chapter "Build script basics" and "More about tasks"
